import { generateSidebar } from 'vitepress-sidebar'

export default generateSidebar([
  {
    documentRootPath: '/1-basics',
    scanStartPath: '',
    resolvePath: '/1-basics/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFiles: ['Cargo.toml'],
    excludeFolders: ['examples', 'target', 'src'],
  },
  {
    documentRootPath: '/2-core',
    scanStartPath: '',
    resolvePath: '/2-core/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFiles: ['Cargo.toml'],
    excludeFolders: ['examples', 'target', 'src'],
  },
  {
    documentRootPath: '/3-data',
    scanStartPath: '',
    resolvePath: '/3-data/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFiles: ['Cargo.toml'],
    excludeFolders: ['examples', 'target', 'src'],
  },
  {
    documentRootPath: '/4-advanced',
    scanStartPath: '',
    resolvePath: '/4-advanced/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFiles: ['Cargo.toml'],
    excludeFolders: ['examples', 'target', 'src'],
  },
  {
    documentRootPath: '/5-projects',
    scanStartPath: '',
    resolvePath: '/5-projects/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFolders: ['target'],
  },
  {
    documentRootPath: '/6-modern',
    scanStartPath: '',
    resolvePath: '/6-modern/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
    excludeFiles: ['Cargo.toml'],
    excludeFolders: ['examples', 'target', 'src'],
  },
  {
    documentRootPath: '/exercises',
    scanStartPath: '',
    resolvePath: '/exercises/',
    useTitleFromFileHeading: true,
    collapsed: true,
    sortMenusOrderByDescending: false,
  },
])
